dist: xenial
language: node_js

base_setup: &base_setup
  before_script:
    - npx lerna bootstrap --no-ci
    - npx run-s build-full

node_js:
  - 10
  - 12

matrix:
  fast_finish: true
  include:
    - <<: *base_setup
      name: 'CI Tests'
      os: linux
      script: npm run ci
    - <<: *base_setup
      name: 'e2e Tests'
      os:
        - linux
        - osx
        - windows
      addons:
        chrome: stable
        firefox: latest
      script: npx run-s test:e2e

deploy:
  provider: script
  script: "gem install compass && npm run docs"
  skip_cleanup: true
  on:
    tags: true
