dist: xenial
language: node_js

base_setup: &base_setup
  node_js:
    - 10
    - 12
  before_script:
    - npx lerna bootstrap --no-ci
    - npx run-s build-full link

e2e_setup: &e2e_setup
  addons:
    chrome: stable
    firefox: latest
  services:
    - xvfb
  script: npx run-s test:e2e

matrix:
  fast_finish: true
  include:
    - <<: *base_setup
      name: 'CI Tests (Node v10)'
      os: linux
      node_js: 10
      script: npm run ci
    - <<: *base_setup
      name: 'CI Tests (Node v12)'
      os: linux
      node_js: 12
      script: npm run ci
    - <<: *base_setup
      <<: *e2e_setup
      name: 'e2e Tests (Linux)'
      os: linux
    - <<: *base_setup
      <<: *e2e_setup
      name: 'e2e Tests (OSX)'
      os: osx
    # Windows on Travis is not stable enough yet
    # - <<: *base_setup
    #   <<: *e2e_setup
    #   name: 'e2e Tests (Windows)'
    #   os: windows

deploy:
  provider: script
  script: "gem install compass && npm run docs"
  skip_cleanup: true
  on:
    tags: true
