dist: xenial
language: node_js

node_js:
  - 10
  - 12

os:
  - linux
  - osx
  - windows

addons:
  chrome: stable
  firefox: latest

script:
  - npm run ci

after_script:
  - ./node_modules/.bin/codecov

deploy:
  provider: script
  script: "gem install compass && npm run docs"
  skip_cleanup: true
  on:
    tags: true
