dist: xenial
language: node_js

matrix:
  fast_finish: true
  include:
    - name: 'CI Tests'
      os: linux
      node_js:
        - 10
        - 12
      script: npm run ci
    - name: 'e2e Tests'
      os:
        - linux
        - osx
        - windows
      addons:
        chrome: stable
        firefox: latest
      script: npx run-s test:e2e

deploy:
  provider: script
  script: "gem install compass && npm run docs"
  skip_cleanup: true
  on:
    tags: true
